name: maven test CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: test with Maven
      run: mvn -B test
    - name : deploy with maven
      if: not contains(github.ref, "SNAPSHOT")
      run: mvn -B deploy -DskipTests
